###################
### Build Steps ###
###################
steps:

  ##########################
  ### Build docker image ###
  ##########################
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/camilla', '.' ]

  #####################################
  ### Push docker image to registry ###
  #####################################
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/$PROJECT_ID/camilla' ]

############
### Tags ###
############
tags: [ 'camilla' ]

#################
### Artifacts ###
#################
images: [ 'gcr.io/$PROJECT_ID/camilla' ]
